name: wedding
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  dio: ^4.0.4
  shared_preferences: ^2.0.11
  image_picker: ^0.8.4+4
  video_thumbnail: ^0.4.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
fonts:
  - family: NotoSansKR
    fonts: 
      - asset: fonts/NotoSansKR-Thin.otf
        weight: 100
      - asset: fonts/NotoSansKR-Light.otf
        weight: 300
      - asset: fonts/NotoSansKR-Regular.otf
        weight: 400
      - asset: fonts/NotoSansKR-Medium.otf
        weight: 500
      - asset: fonts/NotoSansKR-Bold.otf
        weight: 700
      - asset: fonts/NotoSanSKR-Black.otf
        weight: 900